# frozen_string_literal: true
source 'https://rubygems.org'

gem 'thin', '~> 1.7'
gem 'sinatra', '~> 1.4'
gem 'sinatra-contrib', '~> 1.4'
gem 'yajl-ruby', '~> 1.2'
gem 'sequel', '~> 4.8'
gem 'sqlite3', '~> 1.3'
