#!/usr/bin/env ruby
# frozen_string_literal: true
require 'sinatra'
require 'json'
require 'sequel'

set :port, 9494

#
# Model
#
DB = Sequel.sqlite 'db/data.db'
memos = DB[:memos]

unless DB.table_exists? :memos
  DB.create_table :memos do
    primary_key :id
    String :content
  end

  [<<-A, <<-B].each { |content| memos.insert content: content }
Hello, World!\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Cras in bibendum lorem. In viverra erat ipsum, id pretium urna vehicula ut. Proin vel quam ultricies, placerat urna ut, accumsan leo. Vivamus laoreet vestibulum nulla non dictum. Vestibulum non nisl quis risus dictum vestibulum hendrerit ut diam. Sed eget laoreet augue. Integer pulvinar massa scelerisque rhoncus consequat. Vivamus velit mi, suscipit bibendum tincidunt quis, pulvinar a ante.
  A
"Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit..."
  B
end

#
# Controller
#
get '/memos' do
  content_type :json
  memos.all.reverse.to_json
end

post '/memos' do
  content = JSON.parse(request.body.read)['content']

  # No empty memo
  return 400 if !content || content.empty?

  content_type :json
  memos.insert(content: content).to_json
end

put '/memos/:id' do |id|
  content = JSON.parse(request.body.read)['content']

  memos.where(id: id).update content: content
  200
end

delete '/memos/:id' do |id|
  memos.where(id: id).delete
  200
end

if settings.environment != :production
  # Codes below will not be executed in production mode
  get '/' do
    File.read('public/index.html')
  end
end
