#!/usr/bin/env ruby
# frozen_string_literal: true

require 'date'

source = 'data.db'
targetdir = 'backups'
target = "#{targetdir}/#{DateTime.now.strftime '%y%m%d_%H%M%S_%L'}"

puts "   #{source} => #{target}"
`mkdir -p #{targetdir}`
`xz -kc #{source} > #{target}`

if $?.success?
  puts ' * 백업 완료'
else
  puts ' ! 백업 실패'
  puts " - xz has returned '#{$?.exitstatus}'"
  exit 1
end
